### ISSUE TITLE
[Feature]: add text-to-singing 🎤🎵

### ISSUE THREAD

**Issue by funmolde** [Bebra777228/Pol-Litres-RVC#35]
### Description

Hello 😀,
I'd like to suggest adding a text-to-singing voice synthesis feature.
https://github.com/topics/singing-voice-synthesis
Thank you -_-

Привет 😀,
Я хотел бы предложить добавить функцию синтеза голоса из текста в пение.
https://github.com/topics/singing-voice-synthesis
Спасибо -_-

**Comment by Bebra777228** [comment]
Which specific repository are you referring to?

**Comment by funmolde** [comment]
> Which specific repository are you referring to?
 https://github.com/espnet/espnet

**Comment by Bebra777228** [comment]
Most likely, I will not be adding this functionality. However, if you would like to improve the project, it would be great if you could open a PR to implement this feature.
