### ISSUE TITLE
CoverGenLite : есть ли запуск на процессоре?

### ISSUE THREAD

**Issue by PashaHatsune** [Bebra777228/Pol-Litres-RVC#5]
Хотел бы запустить CoverGenLite на своей локальной машине, но к сожалению/счастью, имею карту от АМД. 
Возможен ли запуск хотя бы на процессоре?

**Comment by Bebra777228** [comment]
На данный момент мои программы не поддерживают процессоры, но я работаю над тем, чтобы они могли запускаться на любом оборудовании.
В своей версии разработчика я уже добавил поддержку процессоров. Однако должен признать, что процесс преобразования на них занимает очень много времени — ~30 минут на 3-х минутном аудио.

В будущем я планирую заняться разработкой портативных версий программ. И как обладатель AMD, я буду уделять особое внимание запуску именно на этом виде карт.

**Comment by PashaHatsune** [comment]
Это на каком процессоре столько занимает времени сделать кавер?

**Comment by Bebra777228** [comment]
Ryzen 3 3250U, Ryzen 7 5700X и на гугл колабе запускал, не знаю что там за проц.

1. Ryzen 7 5700X - ~ 12 минут
2. Ryzen 3 3250U - ~ 30 минут
3. Колаб - ~ 58 минут

Тестовая запись - 2:58 (2 минуты 58 секунд).

Прошлый ответ давал проверив только Ryzen 3 3250U, так что чем мощнее проц, тем быстрее будет преобразование. Попробую ещё чуть поработать над этим, может получится оптимизировать. 

UPD:
Узнал на счет процессора на колабе:
Intel(R) Xeon(R) CPU @ 2.20GHz
1 ядро / 1 поток 👍

**Comment by PashaHatsune** [comment]
ага. Получаеется, что на моем intel i5-3570 это будет еще дольше. Штош, тагда будем ждать на амэдэ, если таков будет. Спасибо за ответы!

> Ryzen 3 3250U, Ryzen 7 5700X и на гугл колабе запускал, не знаю что там за проц.
> 
> 1. Ryzen 7 5700X - ~ 12 минут
> 2. Ryzen 3 3250U - ~ 30 минут
> 3. Колаб - ~ 58 минут
> 
> Тестовая запись - 2:58 (2 минуты 58 секунд).
> 
> Прошлый ответ давал проверив только Ryzen 3 3250U, так что чем мощнее проц, тем быстрее будет преобразование. Попробую ещё чуть поработать над этим, может получится оптимизировать.
> 
> UPD: Узнал на счет процессора на колабе: Intel(R) Xeon(R) CPU @ 2.20GHz 1 ядро / 1 поток 👍

**Comment by Player124413** [comment]
https://github.com/user-attachments/assets/cbe23b4c-aa3e-4583-bf14-0c789bcd1736
